export * from './author-graphql';
export * from './category-graphql';
export * from './image-graphql';
export * from './navlink';
export * from './post-graphl';
export * from './slide';
export * from './slug-graphql';
export * from './tag-graphql';
export * from './tool-graphql';